# Statystyka opisowa {#statystyka_opisowa}

## Rozkład jednej cechy

W modelowaniu rynku kapitałowego narzędzia statystyki opisowej są potrzebne, żeby opisać kształtowanie się stóp zwrotu w przeszłości. Z kolei, na podstawie danych z przeszłości można wnioskować o rozkładzie prawdopodobnych stóp zwrotu w przyszłości. Poniżej opisano sposób opisu rozkładu jednej stopy zwrotu, w kolejnej sekcji pokazano miary współzmiennności stóp zwrotu.  

### Średnie

Średnia arytmetyczna to najprostsze i podstawowe narzędzie opisu rozkładu stóp zwrotu. 

Średnia prosta stopa zwrotu netto za okresy od $1$ do $n$ wynosi: 

\begin{equation}  
\bar{R} = \frac{\sum_{i=1}^n R_i}{n}
(\#eq:sredniaR-intext)
\end{equation}

Analogicznie, średnia stopa zwrotu brutto:

\begin{equation}  
\bar{\boldsymbol{\mathcal{R}}} = \frac{\sum_{i=1}^n \boldsymbol{\mathcal{R}}_i}{n} = 1 + \bar{R}
(\#eq:sredniaRp-intext)
\end{equation}

Średnia stopa logarytmiczna:

\begin{equation}  
\bar{r} = \frac{\sum_{i=1}^n r_i}{n}
(\#eq:sredniar-intext)
\end{equation}

W arkuszach kalkulacyjnych korzystamy z funkcji ŚREDNIA (AVERAGE) - [arkusze Google](<https://support.google.com/docs/answer/3093615?hl=pl>), [Excel](<https://support.microsoft.com/pl-pl/office/%C5%9Brednia-funkcja-047bac88-d466-426c-a32b-8f33eb960cf6>)


### Średnia geometryczna, CAGR

Generalna definicja [średniej geometrycznej](<https://pl.wikipedia.org/wiki/%C5%9Arednia_geometryczna>) dla $m$ dodatnich liczb $x_1 - x_n$:

\begin{equation}  
G = \sqrt[n]{\prod_{i=1}^n x_i} = \sqrt[n]{x_1\cdot x_2\cdot \cdot \cdot x_n} = (x_1\cdot x_2\cdot \cdot \cdot x_n)^{1/n}
(\#eq:sredniagx-intext)
\end{equation}

Stopy netto mogą być ujemne, więc generalna definicja nie ma zastosowania. W matematyce finansowej i w praktyce terminu "średnia geometryczna stopa zwrotu (netto)" używa się niekiedy mając na myśli coś nieco innego -- geometryczną średnią ze stóp zwrotu brutto w następujących po sobie okresach pomniejszoną o 1 [@DeFuscoEtAl_2007]:

\begin{equation}  
R_G = \left(\prod_{i=1}^t \boldsymbol{\mathcal{R}}_i\right)^{\frac{1}{t}} - 1 = \left[\prod_{i=1}^t (1+R_i)\right]^{\frac{1}{t}} - 1
(\#eq:sredniagR-intext)
\end{equation}

W przypadku braku dywidend:

\begin{equation}  
R_G = \left(\frac{P_t}{P_0} \right)^{\frac{1}{t}} - 1
(\#eq:sredniagP-intext)
\end{equation}

Jak widać, gdy nie ma dywidend i pojedynczy okres stopy zwrotu wynosi jeden rok, to średnią geometryczną stopę zwrotu netto można utożsamiać ze skumulowanym rocznym wskaźnikiem wzrostu ([CAGR](<https://pl.wikipedia.org/wiki/Skumulowany_roczny_wska%C5%BAnik_wzrostu>)).

Dla logarytmicznych stóp zwrotu nie liczymy średniej geometrycznej. Warto jednak zauważyć, że:

\begin{equation}  
R_G = e^{\bar{r}}-1
(\#eq:sredniaglog-intext)
\end{equation}

W arkuszach kalkulacyjnych nie ma gotowego wzoru na CAGR, mogą się jednak przydać funkcje ŚREDNIA.GEOMETRYCZNA (GEOMEAN) -- [arkusze Google](<https://support.google.com/docs/answer/3094001?hl=pl>), [Excel](<https://support.microsoft.com/pl-pl/office/%C5%9Brednia-geometryczna-funkcja-db1ac48d-25a5-40a0-ab83-0b38980e40d5>) oraz ILOCZYN (PRODUCT) -- [arkusze Google](<https://support.google.com/docs/answer/3093502?hl=pl>), [Excel](<https://support.microsoft.com/pl-pl/office/product-function-e46128aa-0cd8-4a45-915c-6a6f90c06ec8>).


### Wariancja i odchylenie standardowe

Wzór na wariancję pojawia się w dwóch wersjach: dla populacji i dla próby. 

Wzór na wariancję dla populacji o liczebności $N$, na przykładzie prostych stóp zwrotu netto:

\begin{equation}  
\sigma^2_R = \frac{\sum_{i=1}^N \left(R_i-\bar{R}\right)^2}{N}
(\#eq:varR-intext)
\end{equation}

Na wariancję dla próby o liczebności $n$:

\begin{equation}  
s^2_R = \frac{\sum_{i=1}^n \left(R_i-\bar{R}\right)^2}{n-1}
(\#eq:varRs-intext)
\end{equation}

Ponieważ będziemy często traktować wyznaczone dane historyczne jako próbę pozwalającą wnioskować o przyszłości, __w obliczeniach praktycznych będziemy stosować wzór \@ref(eq:varRs-intext)__. 

W arkuszach kalkulacyjnych korzystamy z funkcji WARIANCJA (VAR) -- [arkusze Google](<https://support.google.com/docs/answer/3094063?hl=pl>), [Excel](<https://support.microsoft.com/pl-pl/office/wariancja-funkcja-1f2b7ab2-954d-4e17-ba2c-9e58b15a7da2>), która jest równoznaczna z funkcją WARIANCJA.PRÓBKI (VAR.S) -- [arkusze Google](<https://support.google.com/docs/answer/9387478?hl=pl>), [Excel](<https://support.microsoft.com/pl-pl/office/wariancja-pr%C3%B3bki-funkcja-913633de-136b-449d-813e-65a00b2b990b>). 

Aby obliczyć wariancję w populacji można wykorzystać funkcję WARIANCJA.POPUL/WARIANCJA.POP (VARP/VAR.P) -- [arkusze Google](<https://support.google.com/docs/answer/3094113?hl=pl>), [Excel](<https://support.microsoft.com/pl-pl/office/wariancja-pop-funkcja-73d1285c-108c-4843-ba5d-a51f90656f3a>).

Odchylenie standardowe to pierwiastek z wariancji. Analogicznie, mamy wzór dla populacji i dla próby:

\begin{equation}  
\sigma_R = \sqrt{\sigma^2_R} = \sqrt{\frac{\sum_{i=1}^N \left(R_i-\bar{R}\right)^2}{N}}
(\#eq:sdR-intext)
\end{equation}

\begin{equation}  
s_R = \sqrt{s^2_R} = \sqrt{\frac{\sum_{i=1}^n \left(R_i-\bar{R}\right)^2}{n-1}}
(\#eq:sdRs-intext)
\end{equation}

W arkuszach kalkulacyjnych odchylenie standardowe dla próby wyznaczamy za pomocą funkcji ODCH.STANDARDOWE (STDEV) -- [arkusze Google](<https://support.google.com/docs/answer/3094054?hl=pl>), [Excel](<https://support.microsoft.com/pl-pl/office/odch-standardowe-funkcja-51fecaaa-231e-4bbb-9230-33650a72c9b0>) lub (równoznacznie) ODCH.STANDARD.PRÓBKI (STDEV.S) -- [arkusze Google](<https://support.google.com/docs/answer/9387538?hl=pl>), [Excel](<https://support.microsoft.com/pl-pl/office/odch-standard-pr%C3%B3bki-funkcja-7d69cf97-0c1f-4acf-be27-f3e83904cc23>). 

Odchylenie standardowe dla populacji można obliczyć za pomocą funkcji ODCH.STANDARD.POPUL (STDEVP) -- [arkusze Google](<https://support.google.com/docs/answer/3094105?hl=pl>), [Excel](<https://support.microsoft.com/pl-pl/office/odch-standard-popul-funkcja-1f7c1c88-1bec-4422-8242-e9f7dc8bb195>) albo ODCH.STAND.POPUL (STDEV.P)-- [arkusze Google](<https://support.google.com/docs/answer/9387532?hl=pl>), [Excel](<https://support.microsoft.com/pl-pl/office/odch-stand-popul-funkcja-6e917c05-31a0-496f-ade7-4f4e7462f285>). 
 
### Skośność/asymetria

Współczynnik asymetrii oparty na momentach oblicza się w następujący sposób:

\begin{equation}  
g_{1(R)} = \frac{1}{n}\sum_{i=1}^n\left(\frac{R_i-\bar{R}}{\sigma_R}\right)^3
(\#eq:skewRg1-intext)
\end{equation}

Powyższy wzór można uznać za analogiczny do wzorów na wariancję i odchylenie standardowe populacji. 

Zmodyfikowany współczynnik asymetrii ma następujący wzór:

\begin{equation}  
G_{1(R)} = \frac{\sqrt{n(n-1)}}{n-2}g_{1(R)}
(\#eq:skewRG1-intext)
\end{equation}

Współczynnik asymetrii mierzy, które ramię rozkładu: lewe -- poniżej średniej (ujemne wartości współczynnika) czy prawe -- powyżej średniej (wartości dodatnie) jest bardziej wyciągnięte. Można stwierdzić, że przypadku stóp zwrotu ujemny współczynnik wskazuje na większe prawdopodobieństwo skrajnych strat, zaś dodatni na większe prawdopodobieństwo skrajnych zysków. 

W arkuszach kalkulacyjnych zmodyfikowany współczynnik asymetrii ($G_1$) można obliczyć za pomocą funkcji SKOŚNOŚĆ (SKEW) -- [arkusze Google](<https://support.google.com/docs/answer/3094101?hl=pl>), [Excel](<https://support.microsoft.com/pl-pl/office/sko%C5%9Bno%C5%9B%C4%87-funkcja-bdf49d86-b1ef-4804-a046-28eaea69c9fa>), zaś współczynnik $g_1$ uzyskamy stosując funkcję SKOŚNOŚĆ.P (SKEW.P) -- [arkusze Google](<https://support.google.com/docs/answer/9368569?hl=pl>), [Excel](<https://support.microsoft.com/pl-pl/office/sko%C5%9Bno%C5%9B%C4%87-p-funkcja-76530a5c-99b9-48a1-8392-26632d542fcb>).


### Kurtoza

Współczynnik ekscesu nazywany też kurtozą nadwyżkową/względną wyznacza się za pomocą następującego wzoru: 

\begin{equation}  
g_{2(R)} = \frac{1}{n}\sum_{i=1}^n\left(\frac{R_i-\bar{R}}{\sigma_R}\right)^4-3
(\#eq:kurtRg2-intext)
\end{equation}

Powyższy wzór można traktować jako wzór dla populacji. Wzór dla próby ma najczęściej następującą postać: 

\begin{equation}  
G_{2(R)} = \frac{n-1}{(n-2)(n-3)}\left[(n+1)g_{2(R)}+6\right]
(\#eq:kurtRsg2-intext)
\end{equation}

W niektórych pakietach statystycznych spotyka się również wzór: 

\begin{equation}  
b_{2(R)} = \frac{1}{n}\sum_{i=1}^n\left(\frac{R_i-\bar{R}}{s_R}\right)^4-3
(\#eq:kurtRb2-intext)
\end{equation}

W arkuszach kalkulacyjnych funkcja KURTOZA (KURT) oblicza współczynnik $G_2$ zgodnie ze wzorem \@ref(eq:kurtRsg2-intext) -- [arkusze Google](<https://support.google.com/docs/answer/3093634?hl=pl>), [Excel](<https://support.microsoft.com/pl-pl/office/kurtoza-funkcja-bc3a265c-5da4-4dcb-b7fd-c237789095ab>). Współczynniki $g_2$ i $b_2$ można obliczyć stosując funkcję na średnią i odchylenie standardowe oraz [formuły tablicowe](<https://support.microsoft.com/pl-pl/office/tworzenie-formu%C5%82y-tablicowej-e43e12e0-afc6-4a12-bc7f-48361075954d>). 

Kurtoza (współczynnik ekscesu) mierzy intensywność wartości skrajnych w porównaniu z wartościami skrajnymi w rozkładzie normalnym. 

<!-- ### Mediana -->

<!-- ### Kwantyle -->

## Współzależność cech

### Kowariancja

Wzór na kowariancję dla populacji o liczebności $N$, na przykładzie dwóch szeregów danych (np. stóp zwrotu) $R_i$ i $S_i$:

\begin{equation}  
\sigma_{RS} = \frac{\sum_{i=1}^N \left(R_i-\bar{R}\right)\left(S_i-\bar{S}\right)}{N}
(\#eq:covarR-intext)
\end{equation}

Jest to wzór "dla populacji". 

W arkuszach można zastosować funkcję KOWARIANCJA (COVAR) -- [arkusze Google](<https://support.google.com/docs/answer/3093993?hl=pl>), [Excel](<https://support.microsoft.com/pl-pl/office/kowariancja-funkcja-50479552-2c03-4daf-bd71-a5ab88b2db03>) lub KOWARIANCJA.POPUL (COVARIANCE.P) -- -- [arkusze Google](<https://support.google.com/docs/answer/9386301?hl=pl>), [Excel](<https://support.microsoft.com/pl-pl/office/kowariancja-popul-funkcja-6f0e1e6d-956d-4e4b-9943-cfef0bf9edfc>).

Dla próby analogiczny wzór wygląda następująco:

\begin{equation}  
s_{RS} = \frac{\sum_{i=1}^n \left(R_i-\bar{R}\right)\left(S_i-\bar{S}\right)}{n-1}
(\#eq:covarsR-intext)
\end{equation}

W arkuszach używamy funkcji KOWARIANCJA.PRÓBKI (COVARIANCE.S) -- [arkusze Google](<https://support.google.com/docs/answer/9365675?hl=pll>), [Excel](<https://support.microsoft.com/pl-pl/office/kowariancja-pr%C3%B3bki-funkcja-0a539b74-7371-42aa-a18f-1f5320314977>).


### Korelacja

Korelacja to zestandaryzowana kowariancja. Można ją policzyć zarówno na podstawie wzorów na kowariancję i wariancję z populacji:

\begin{equation}  
\rho_{RS} = \frac{\sigma_{RS}}{\sigma_R \sigma_S}
(\#eq:corrho-intext)
\end{equation}

jak i na kowariancję/wariancję z próbki:

\begin{equation}  
r_{RS} = \frac{s_{RS}}{s_R s_S}
(\#eq:corr-intext)
\end{equation}

Otrzymane wyniki są takie same. W arkuszach kalkulacyjnych stosujemy funkcję WSP.KORELACJI (CORREL) -- [arkusze Google](<https://support.google.com/docs/answer/3093990?hl=pl>), [Excel](<https://support.microsoft.com/pl-pl/office/wsp-korelacji-funkcja-995dcef7-0c0a-4bed-a3fb-239d7b68ca92>) lub identyczną w działaniu funkcję PEARSON -- [arkusze Google](<https://support.google.com/docs/answer/3094092?hl=pl>), [Excel](<https://support.microsoft.com/pl-pl/office/pearson-funkcja-0c3e30fc-e5af-49c4-808a-3ef66e034c18>).

## Ćwiczenia

<!--Linton 4 
Recently, Warren Buffett has predicted that the Dow Jones index will exceed one million in a hundred years time. Given that the current level of the index is 22400, what annual rate of return is he assuming?

https://www.cnbc.com/2017/09/21/dow-1-million-warren-buffett-says-it-can-happen.html

-->

:::{.exercise #linton4}
[@Linton_2019]
W 2017 roku Warren Buffett [przewidział, że indeks Dow Jones przekroczy milion w ciągu stu lat](<https://www.cnbc.com/2017/09/21/dow-1-million-warren-buffett-says-it-can-happen.html>). Biorąc pod uwagę, że w momencie wygłaszania tej prognozy wartość indeksu DJIA wynosiła 22375, jaką zakładał roczną stopę zwrotu?
:::

:::{.exercise #sbbi}
SBBI to raport przygotowywany przez CFA Institute, który pokazuje stopy zwrotu rynku amerykańskiego dla dużych spółek (__Large-Cap Stocks__), mniejszych spółek (__Small-Cap Stocks__), obligacji korporacyjnych (__Long-term Corp Bonds__), długoterminowych obligacji rządowych (__Long-term Gov't Bonds__), średnioterminowych obligacji rządowych (__Inter-term Gov't Bonds__), krótkoterminowych bonów skarbowych (__U.S. Treasury Bills__) oraz wskaźnik inflacji (__Inflation__). 

Roczne stopy zwrotu dla lat 1926-2015 są dostępne pod poniższym linkiem: <https://docs.google.com/spreadsheets/d/1rfE78O1POHpQl15AQU2gtp15cV7h9JLNeAkRN66TNqE/edit?usp=sharing>

Dla każdej z tych grup aktywów wyznacz dla okresu 1926-2015: 

a) średnią prostą stopę zwrotu netto

b) średnią geometryczną prostą stopę zwrotu netto (CAAGR)

c) odchylenie standardowe prostych stóp zwrotu netto

d) skośność i kurtozę prostych stóp zwrotu netto

e) średnią logarytmiczną stopę zwrotu

f) odchylenie standardowe logartymicznych stóp zwrotu

g) skośność i kurtozę logarytmicznych stóp zwrotu
:::

:::{.exercise #ticker-of-choice1}
Dla wybranej spółki ściągnij dane z bazy yahoo i wyznacz statystyki określone w poprzednim zadaniu dla dziennych stóp zwrotu i miesięcznych stóp zwrotu. Użyj cen adjusted close.   
:::

:::{.exercise #ticker-of-choice2}
Dla wybranej spółki sprawdź, czy dzienne stopy zwrotu obejmujące weekend są średnio wyższe niż dzienne stopy zwrotu w inne dni tygodnia. Czy odchylenie standardowe dziennych stóp zwrotu obejmujących weekend jest wyższe?   
:::

:::{.exercise #ticker-of-choice3}
Sprawdź korelację pomiędzy stopami zwrotu netto dwóch wybranych spółek na podstawie (a) miesięcznych (b) dziennych stóp zwrotu netto. 
:::

