# Modele wędrówki cen {#zmianycen}

## Model siatki dwumianowej

``` {r bintree, echo=FALSE, fig.cap='Model siatki dwumianowej'}
library(ggplot2)
ar<-data.frame(x0=c(0,0,1,1,1,1,2,2,2,2,2,2,3,3,3,3,3,3,3,3)+0.05,
                   y0=c(0,0,1,1,-1,-1,2,2,0,0,-2,-2,3,3,1,1,-1,-1,-3,-3),
                   xend=c(1,1,2,2,2,2,3,3,3,3,3,3,4,4,4,4,4,4,4,4)-0.05,
                   yend=c(1,-1,2,0,0,-2,3,1,1,-1,-1,-3,4,2,2,0,0,-2,-2,-4))

ar$xp<-(ar$x0+ar$xend)/2
ar$yp<-(ar$y0+ar$yend)/2
ar$labelp<-rep(c('p', '1-p'),10)

po<-data.frame(x0=c(0,1,1,2,2,2,3,3,3,3,4,4,4,4,4)
                   , y0=c(0,1,-1,2,0,-2,3,1,-1,-3,4,2,0,-2,-4)
              , label0=c('S[0]', 'S[0]*u', 'S[0]*d', 
                         'S[0]*u^2', 'S[0]*ud', 'S[0]*d^2', 
                         'S[0]*u^3', 'S[0]*u^2*d', 'S[0]*u*d^2', 'S[0]*d^3', 
                         'S[0]*u^4', 'S[0]*u^3*d', 'S[0]*u^2*d^2', 'S[0]*u*d^3', 'S[0]*d^4'))


ggplot(aes(x=x0, y=y0+.4), data=po) + 
  theme_void() +
  geom_segment(aes(x = x0, y = y0, xend = xend, yend = yend),
               data=ar, 
               arrow = arrow(type='closed', angle=7, length=unit(.15,'inch'))) +
  geom_point(aes(x=x0, y=y0), data=po) +
  geom_text(aes(label=label0), parse=TRUE) +
  geom_text(aes(x=xp, y=yp+.3, label=labelp), data=ar, col='grey')

```

Jeżeli:

- $\nu$ to oczekiwana roczna stopa wzrostu:

\begin{equation}
\nu = E[ln(S_T/S_0)]
(\#eq:lattice-E)
\end{equation}, 

gdzie $S_T$ to cena akcji po roku, a $S_0$ to bieżąca cena;

- $\sigma$ to roczne odchylenie standardowe stopy wzrostu (jako miara jej niepewności):

\begin{equation}
\sigma = \sqrt{Var[ln(S_T/S_0)]}
(\#eq:lattice-sigma)
\end{equation}

- okres $\Delta t$ jest znikomo mały w porównaniu z 1 rokiem, 

to parametry modelu siatki dwumianowej można wyznaczyć w następujący sposób:

\begin{equation}
p = \frac{1}{2} + \frac{1}{2} \cdot \frac{\nu}{\sigma}\sqrt{\Delta t}
(\#eq:lattice-p)
\end{equation}

\begin{equation}
u = e^{\sigma\sqrt{\Delta t}}
(\#eq:lattice-u)
\end{equation}

\begin{equation}
u = e^{-\sigma\sqrt{\Delta t}}
(\#eq:lattice-d)
\end{equation}

[Model siatki dwumianowej w arkuszu kalkulacyjnym](<https://www.youtube.com/watch?v=nGLaMDRTWuY>). 

## Model addytywny

Model addytywny to model z czasem dyskretnym, to znaczy model pokazujący cenę dla równo oddalonych od siebie punktów w czasie (momentów). 

Załóżmy, że mamy $N+1$ momentów, oznaczamy je przez $k$ ($k = 0, 1, 2, ..., N$). Cena aktywów w momencie $k+1$ ($S(k+1)$ zależy od $S(k)$ (ceny w poprzednim momencie) i wynosi, zgodnie z tym modelem: 

\begin{equation}
S(k+1) = a S(k) + u(k), 
(\#eq:additive-intext)
\end{equation}

gdzie $a$ to pewna stała, a u(k) to zakłócenia losowe. 

Załóżmy, że zakłócenia u(k) mają taki sam rozkład rozkład normalny, wartość oczekiwaną równą zero, wariancję $\sigma^2$ i są niezależne. Można pokazać, że przy takich założeniach wartość oczekiwana ceny po $k$ okresach wynosi:

\begin{equation}
E(S(k)) = a^k S(0), 
(\#eq:additive-E)
\end{equation}

Wariancja zaś wynosi:

\begin{equation}
$$V(S(k)) = \sigma^2\sum_{i=0}^k a^{2i} . $$
(\#eq:additive-V)
\end{equation}

Parametry rozkładu prostych $k$-okresowych stóp zwrotu netto są następujące. Wartość oczekiwana:

$$ E\left[R(k)\right] = E\left[\frac{S(k)}{S(0)}-1\right] =  a^k - 1 $$
Wariancja:
$$ V\left[R(k)\right] = V\left[\frac{S(k)}{S(0)}\right] = \frac{\sigma^2\sum_{i=0}^k a^{2i}}{[S(0)]^2}  $$

Model addytywny jest prosty, jednak nie przystaje do rzeczywistości w dwóch podstawowych aspektach:

1. Według modelu ceny mogą spaść poniżej zera (w rzeczywistości zwykle nie mogą). 

2. Odchylenie standardowe jest stałe niezależnie od rzędu wielkości ceny (jeżeli cena wzrośnie 100-krotnie, odchylenie standardowe względem ceny będzie 100 razy mniejsze). 

## Model multiplikatywny

Model multiplikatywny ma postać:

$$S(k+1) = S(k) \cdot u(k), $$


gdzie u(k) to zmienna zakłócająca inna niż w przypadku modelu addytywnego. 

W postaci logarytmicznej:

$$\ln S(k+1) = \ln S(k) + \ln u(k)$$
Zakładamy, że zmienne losowe 

$$ w(k) = \ln u(k) $$

mają rozkłąd normalny, są wzajemnie niezależne, a wartość oczekiwana każdej z nich wynosi $E(w(k)) = \nu$ przy wariancji równej $\sigma^2$. 

Czynnik zakłócający $u(k)$ można zapisać jako 

$$ u(k) = e^{w(k)}$$

ma rozkład logarytmiczno-normalny. 

Model multiplikatywny pozwala pozbyć się dwóch poprzednio wspomnianych problemów modelu addytywnego: ceny nie mogą spaść poniżej zera i zmienna u(k) powoduje, że rozproszenie stóp zwrotu rośnie z ceną. 

$$ E(ln S(k)) = \ln S(0) + \nu k $$
$$ V(\ln(S(k))) = k \sigma^2 $$


$$ E[r(k)] = E\left[ln \frac{S(k)}{S(0)}\right] =  k\nu $$

$$ V[r(k)] = V\left[\ln \frac{S(k)}{S(0)}\right] = V\left[ln S(k)-S(0)\right] = k \sigma^2 $$


## Ćwiczenia
:::{.exercise #lintonlattice1}
[@Linton_2019] Akcja, której cena bieżąca wynosi S(0)=100, ma oczekiwaną logarytmiczną stopę zwrotu $\nu$ równą = 12\%. Zmienność tej stopy wynosi $\sigma$ = 20\%. Wyznacz odpowiednie wartości parametrów niezbędnych do zbudowania siatki dwumianowej pokazującej zmiany cen tej akcji, jeżeli okresem podstawowym miałyby być 3 miesiące. Narysuj tę siatkę dla pierwszego roku, uzupełniając wartości w poszczególnych węzłach. Jakie jest prawdopodobieństwo osiągnięcia poszczególnych węzłów końcowych?
:::

:::{.exercise #sim1}
Przygotuj symulację procesu zmieny cen według modelu addytywnego i multiplikatywnego w arkuszu kalkulacyjnym. 
:::

