# (APPENDIX) Dodatki {-}

# Ćwiczenia {#cwiczenia}

## Stopy zwrotu
<!-- Ruppert 2.6.3
Suppose the price of a stock at times 1, 2, and 3 are P1 = 95, P2 = 103, and P3 = 98. Find r3(2).
-->

:::{.exercise #rup263}
Załóżmy, że kurs pewnej akcji w momencie 1, 2 i 3 wynosił $P_1$=95, $P_2$=103 i $P_3$ = 98. 
Znajdź $r_3(2)$.
:::


<!-- Ruppert 2.6.4
The prices and dividends of a stock are given in the table below.
(a) What is R2?
(b) What is R4(3)?
(c) What is r3?
t Pt Dt
1 52 0.2
2 54 0.2
3 53 0.2
4 59 0.25
-->

:::{.exercise #rup264}
Ceny akcji i dywidendy pewnej spółki zostały podane w poniższej tabeli.

(a) Ile wynosi $R_2$?

(b) Ile wynosi $R_4(3)$?

(c) Ile wynosi $r_3$?

```{r echo=FALSE}  
df<-data.frame(t=1:4, Pt=c(52, 54, 53, 59), Dt=c(.2, .2, .2, .25))
colnames(df)<-c("$t$", "$P_t$", "$D_t$")
knitr::kable(df)
```
:::


<!-- Ruppert 2.6.1
The daily log returns on a stock are independent and normally distributed with mean 0.001 and standard deviation 0.015. Suppose you buy $1000 worth of this stock.
(a) What is the probability that after one trading day your investment  is worth less than $990? (Note: The R function pnorm will compute a normal CDF, so, for example, pnorm(0.3,mean=0.1,sd=0.2) is the normal CDF with mean 0.1 and standard deviation 0.2 evaluated at
0.3.)
(b) What is the probability that after five trading days your investment is worth less than $990?
-->

:::{.exercise #rup261}
Dzienne zwroty z akcji ZZZ są niezależne i mają rozkład normalny ze średnią 0,001 i odchyleniem standardowym 0,015. Załóżmy, że kupujemy te akcje za 1000 USD.
(a) Jakie jest prawdopodobieństwo, że po jednym dniu handlowym inwestycja będzie warta mniej niż 990 USD? 
(b) Jakie jest prawdopodobieństwo, że po pięciu dniach handlowych inwestycja będzie warta mniej niż 990 USD?
:::

<!-- Ruppert 2.6.2
The yearly log returns on a stock are normally distributed with mean 0.1
and standard deviation 0.2. The stock is selling at $100 today. What is
the probability that one year from now it is selling at $110 or more?
-->

:::{.exercise #rup262}
Roczne logarytmiczne zwroty akcji spółki PRS mają rozkład normalny ze średnią równą 0,1 i odchyleniem standardowym równym 0,2. Dzisiejszy kurs akcji spółki PRS to 100 USD. Jakie jest prawdopodobieństwo, że za rok kurs będzie wynosił 110 USD lub więcej?
:::


<!--Linton 4 
Recently, Warren Buffett has predicted that the Dow Jones index will exceed one million in a hundred years time. Given that the current level of the index is 22400, what annual rate of return is he assuming?

https://www.cnbc.com/2017/09/21/dow-1-million-warren-buffett-says-it-can-happen.html

-->

:::{.exercise #linton4}
W 2017 roku Warren Buffett przewidział, że indeks Dow Jones przekroczy milion w ciągu stu lat. Biorąc pod uwagę, że w momencie wygłaszania tej prognozy wartość indeksu DJIA wynosiła 22375, jaką zakładał roczną stopę zwrotu?
:::






<!--Luenberger 1. 
Two dice are rolled and the two resulting values are multiplied together to form the quantity $z$. What are the expected value and the variance of the random variable $z$? (Hint: Use the independence of the two separate dice)-->

:::{.exercise #diceproduct}
Rzucamy dwiema kośćmi do gry i mnożymy otrzymane wyniki: w ten sposób powstaje zmienna $z$. Jaka jest wartość oczekiwana i wariancja zmiennej losowej $z$? (Wskazówka: rzuty koścmi należy traktować jako zdarzenia niezależne.)
:::


